version: 2

sources:
  - name: airbyte_raw
    database: dw_tyg
    schema: public
    tables:
      - name: ventas
      - name: recepciones
      - name: productos
      - name: oficinas
      - name: vendedores
      - name: asesores
      - name: activaciones
      - name: metas
